
[font]
size = 12

[font.offset]
y = 4

[window]
decorations = "buttonless"
opacity = 1
option_as_alt = "Both"
startup_mode = "Maximized"

[window.padding]
x = 9

[general]
import = ["/Users/stasuz/.config/alacritty/themes/themes/gruvbox_dark.toml", "/Users/stasuz/.config/alacritty/keybindings.toml"]
