
[font]
size = 12

[font.offset]
y = 4

[window]
decorations = "buttonless"
opacity = 1.0
blur = true
option_as_alt = "Both"
startup_mode = "Maximized"

[window.padding]
x = 9

[general]
#import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml", "~/.config/alacritty/keybindings.toml"]
import = ["~/.config/alacritty/themes/themes/ayu_dark.toml", "~/.config/alacritty/keybindings.toml"]
