
[font]
size = 12

[font.offset]
y = 4

[window]
decorations = "buttonless"
opacity = 0.8
blur = true
option_as_alt = "Both"
# startup_mode = "Maximized"
dimensions = { columns = 262, lines = 65 }
position = { x = 700, y = 265 }

[window.padding]
x = 9

[general]
#import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml", "~/.config/alacritty/keybindings.toml"]
import = ["~/.config/alacritty/themes/themes/ayu_dark.toml", "~/.config/alacritty/keybindings.toml"]
