[keyboard]
# Skip word left
[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

# Skip word right
[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

# Home
[[keyboard.bindings]]
chars = "\u001BOH"
key = "Left"
mode = "AppCursor"
mods = "Command"

# End
[[keyboard.bindings]]
chars = "\u001BOF"
key = "Right"
mode = "AppCursor"
mods = "Command"

# Delete line
[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Command"

# Delete word
[[keyboard.bindings]]
chars = "\u001B\u007F"
key = "Back"
mods = "Alt"
